/** README.md (the profile) and preview.html (local review only). */

import { DOORS, IDENTITY, UPSTREAM } from '../content.ts';
import { fileName, type Figure } from './index.ts';
import { esc } from './svg.ts';

const NARROW_MEDIA = '(max-width: 600px)';

/**
 * Source order matters. GitHub resolves any media query that mentions
 * prefers-color-scheme against its own theme setting, so that feature is never
 * combined with another condition. The phone source is width-only and points
 * at a figure that switches palette internally.
 */
function picture(fig: Figure): string {
  return [
    '<picture>',
    `  <source media="${NARROW_MEDIA}" srcset="dist/${fileName(fig.id, 'narrow')}">`,
    `  <source media="(prefers-color-scheme: dark)" srcset="dist/${fileName(fig.id, 'dark')}">`,
    `  <img src="dist/${fileName(fig.id, 'light')}" width="100%" alt="${esc(fig.alt)}">`,
    '</picture>',
  ].join('\n');
}

export function readme(figs: ReadonlyArray<Figure>): string {
  const blocks: string[] = ['<!-- Generated by generator/src/main.ts. Edit the generator, not this file. -->'];
  for (const fig of figs) {
    blocks.push(picture(fig));
    if (fig.link) blocks.push(`<p><a href="${fig.link.href}">${esc(fig.link.text)}</a></p>`);
    if (fig.id === 'specs') blocks.push(`<p>Upstream: <a href="${UPSTREAM.href}">openapi-typescript #2865</a> (open pull request)</p>`);
    if (fig.id === 'terms') {
      const [job, project] = DOORS;
      blocks.push(
        `<p><a href="${job.href}">${esc(job.title)}: ${esc(IDENTITY.email)}</a><br>\n` +
          `<a href="${project.href}">${esc(project.title)}: ${esc(IDENTITY.site)}</a> · ${esc(IDENTITY.phone)}</p>`,
      );
    }
  }
  blocks.push(
    '<sub>Figures are rendered daily from read-only GitHub data by <a href="generator/">the generator in this repository</a>. ' +
      'Private work appears only as counts, dates and short commit SHAs.</sub>',
  );
  return blocks.join('\n\n') + '\n';
}

/**
 * Side-by-side review page: desktop and phone, light and dark, with a replay
 * control. The phone columns show the same narrow file twice; `color-scheme`
 * on the <img> sets the scheme its internal media query sees (Chrome, Firefox).
 */
export function preview(figs: ReadonlyArray<Figure>): string {
  const column = (theme: 'light' | 'dark', narrow: boolean) => {
    const imgs = figs
      .map((f) => `<img src="dist/${fileName(f.id, narrow ? 'narrow' : theme)}" alt="${esc(f.alt)}">`)
      .join('\n');
    const label = `${narrow ? 'Phone, 375px' : 'Desktop, 830px column'} · ${theme}`;
    return `<section class="col ${theme} ${narrow ? 'phone' : 'desk'}"><h2>${label}</h2><div class="frame">${imgs}</div></section>`;
  };
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Profile preview</title>
<style>
  body { margin: 0; padding: 24px 16px 48px; background: #E9E9E6; color: #111; font: 14px/1.4 system-ui, sans-serif; }
  header { display: flex; gap: 16px; align-items: baseline; flex-wrap: wrap; margin-bottom: 20px; }
  h1 { font-size: 18px; margin: 0; }
  button { font: inherit; padding: 4px 10px; border: 1px solid #111; border-radius: 2px; background: #fff; cursor: pointer; }
  .row { display: flex; gap: 24px; align-items: flex-start; overflow-x: auto; padding-bottom: 12px; margin-bottom: 24px; }
  h2 { font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: .08em; margin: 0 0 8px; color: #555; }
  .frame { display: flex; flex-direction: column; gap: 16px; padding: 16px; }
  .desk .frame { width: 830px; }
  .phone .frame { width: 343px; }
  .light .frame { background: #FFFFFF; }
  .dark .frame { background: #0D1117; }
  .light img { color-scheme: light; }
  .dark img { color-scheme: dark; }
  .frame img { width: 100%; display: block; }
</style>
</head>
<body>
<header><h1>GitHub profile: local preview</h1><span>Backgrounds match GitHub's light and dark themes.</span><button id="replay" type="button">Replay animation</button></header>
<div class="row">${column('light', false)}${column('dark', false)}</div>
<div class="row">${column('light', true)}${column('dark', true)}</div>
<script>
  document.getElementById('replay').addEventListener('click', () => {
    const t = Date.now();
    for (const img of document.images) img.src = img.src.split('?')[0] + '?' + t;
  });
</script>
</body>
</html>
`;
}
